// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTarefas.Persistence.Contextos;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyTarefas.Persistence.Migrations
{
    [DbContext(typeof(MyTarefasContext))]
    partial class MyTarefasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("MyTarefas.Domain.Acompanhamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("HorasPrevistas")
                        .HasColumnType("text");

                    b.Property<string>("Saldo")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Acompanhamentos");

                    b.HasData(
                        new
                        {
                            Id = 2080741784L,
                            CardId = 878851122L,
                            HorasPrevistas = "00:30",
                            Saldo = "00:10",
                            Status = 1
                        },
                        new
                        {
                            Id = 1911213533L,
                            CardId = 1534802998L,
                            HorasPrevistas = "00:30",
                            Saldo = "00:10",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MyTarefas.Domain.AcompanhamentoUsuario", b =>
                {
                    b.Property<long>("AcompanhamentoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("AcompanhamentoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AcompanhamentoUsuario");

                    b.HasData(
                        new
                        {
                            AcompanhamentoId = 2080741784L,
                            UsuarioId = 1855701605L
                        });
                });

            modelBuilder.Entity("MyTarefas.Domain.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPrevisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Projeto")
                        .HasColumnType("text");

                    b.Property<long>("TarefaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<int>("posicaoVertical")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 878851122L,
                            DataPrevisao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usar a branch master, fazer pull, após isso...",
                            Projeto = "Company",
                            TarefaId = 1712405553L,
                            Titulo = "Criar Migration",
                            posicaoVertical = 0
                        },
                        new
                        {
                            Id = 416741983L,
                            DataPrevisao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "aaaaaaaaa",
                            Projeto = "Company",
                            TarefaId = 1712405553L,
                            Titulo = "testee",
                            posicaoVertical = 1
                        },
                        new
                        {
                            Id = 1158010731L,
                            DataPrevisao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "bbbbbbbbbbbbbb",
                            Projeto = "Company",
                            TarefaId = 1712405553L,
                            Titulo = "bbbbbbbbbb",
                            posicaoVertical = 2
                        },
                        new
                        {
                            Id = 499607459L,
                            DataPrevisao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "ccccccccccccc",
                            Projeto = "Company",
                            TarefaId = 1712405553L,
                            Titulo = "cccccccccc",
                            posicaoVertical = 4
                        },
                        new
                        {
                            Id = 1534802998L,
                            DataPrevisao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Colunas utilizadas: Código, nome, Descrição...",
                            Projeto = "Company",
                            TarefaId = 1095109455L,
                            Titulo = "Listagem de clientes",
                            posicaoVertical = 2
                        });
                });

            modelBuilder.Entity("MyTarefas.Domain.Departamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("MyTarefas.Domain.Tarefa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Id = 1712405553L,
                            Descricao = "Aguardando"
                        },
                        new
                        {
                            Id = 336490917L,
                            Descricao = "Em Andamento"
                        },
                        new
                        {
                            Id = 125802249L,
                            Descricao = "Pendência"
                        },
                        new
                        {
                            Id = 93663805L,
                            Descricao = "Finalizado"
                        },
                        new
                        {
                            Id = 1095109455L,
                            Descricao = "Outros"
                        });
                });

            modelBuilder.Entity("MyTarefas.Domain.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1855701605L,
                            Descricao = "Carlos"
                        });
                });

            modelBuilder.Entity("MyTarefas.Domain.Acompanhamento", b =>
                {
                    b.HasOne("MyTarefas.Domain.Card", null)
                        .WithOne("Acompanhamento")
                        .HasForeignKey("MyTarefas.Domain.Acompanhamento", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTarefas.Domain.AcompanhamentoUsuario", b =>
                {
                    b.HasOne("MyTarefas.Domain.Acompanhamento", "Acompanhamento")
                        .WithMany("AcompanhamentosUsuarios")
                        .HasForeignKey("AcompanhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyTarefas.Domain.Usuario", "Usuario")
                        .WithMany("AcompanhamentosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyTarefas.Domain.Card", b =>
                {
                    b.HasOne("MyTarefas.Domain.Tarefa", "Tarefa")
                        .WithMany("Cards")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("MyTarefas.Domain.Departamento", b =>
                {
                    b.HasOne("MyTarefas.Domain.Card", null)
                        .WithOne("Departamento")
                        .HasForeignKey("MyTarefas.Domain.Departamento", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyTarefas.Domain.Acompanhamento", b =>
                {
                    b.Navigation("AcompanhamentosUsuarios");
                });

            modelBuilder.Entity("MyTarefas.Domain.Card", b =>
                {
                    b.Navigation("Acompanhamento");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("MyTarefas.Domain.Tarefa", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MyTarefas.Domain.Usuario", b =>
                {
                    b.Navigation("AcompanhamentosUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
